/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-08-22 12:39:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class goodsEnroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/admin/../includes/admin/header.jsp", Long.valueOf(1629007006336L));
    _jspx_dependants.put("/WEB-INF/views/admin/../includes/admin/footer.jsp", Long.valueOf(1629634897347L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>VinShop</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/admin/goodsEnroll.css\">\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.4.1.js\"\r\n");
      out.write("  integrity=\"sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.ckeditor.com/ckeditor5/28.0.0/classic/ckeditor.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	#result_card img{\r\n");
      out.write("		max-width: 100%;\r\n");
      out.write("	    height: auto;\r\n");
      out.write("	    display: block;\r\n");
      out.write("	    padding: 5px;\r\n");
      out.write("	    margin-top: 10px;\r\n");
      out.write("	    margin: auto;	\r\n");
      out.write("	}\r\n");
      out.write("	#result_card {\r\n");
      out.write("		position: relative;\r\n");
      out.write("	}\r\n");
      out.write("	.imgDeleteBtn{\r\n");
      out.write("	    position: absolute;\r\n");
      out.write("	    top: 0;\r\n");
      out.write("	    right: 5%;\r\n");
      out.write("	    background-color: #ef7d7d;\r\n");
      out.write("	    color: wheat;\r\n");
      out.write("	    font-weight: 900;\r\n");
      out.write("	    width: 30px;\r\n");
      out.write("	    height: 30px;\r\n");
      out.write("	    border-radius: 50%;\r\n");
      out.write("	    line-height: 26px;\r\n");
      out.write("	    text-align: center;\r\n");
      out.write("	    border: none;\r\n");
      out.write("	    display: block;\r\n");
      out.write("	    cursor: pointer;	\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        <div class=\"wrap\">\r\n");
      out.write("            <!-- gnv_area -->	\r\n");
      out.write("            <div class=\"top_gnb_area\">\r\n");
      out.write("                <ul class=\"list\">	\r\n");
      out.write("                    <li><a href=\"/main\">메인 페이지</a></li>\r\n");
      out.write("                    <li><a href=\"/member/logout.do\">로그아웃</a></li>\r\n");
      out.write("                    <li><a href=\"/board/list\">고객센터</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- top_subject_area -->\r\n");
      out.write("            <div class=\"admin_top_wrap\">\r\n");
      out.write("                <span>관리자 페이지</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- contents-area -->\r\n");
      out.write("            <div class=\"admin_wrap\">\r\n");
      out.write("                <!-- 네비영역 -->\r\n");
      out.write("                <div class=\"admin_navi_wrap\">\r\n");
      out.write("	              <ul>\r\n");
      out.write("	                  <li >\r\n");
      out.write("	                      <a class=\"admin_list_01\" href=\"/admin/goodsEnroll\">상품 등록</a>\r\n");
      out.write("	                  </li>\r\n");
      out.write("	                  <li>\r\n");
      out.write("	                      <a class=\"admin_list_02\" href=\"/admin/goodsManage\">상품 관리</a>\r\n");
      out.write("	                  </li>\r\n");
      out.write("	                  <lI>\r\n");
      out.write("	                      <a class=\"admin_list_03\" href=\"/admin/memberManage\">회원 관리</a>         \r\n");
      out.write("	                  </lI>\r\n");
      out.write("	                  <lI>\r\n");
      out.write("	                      <a class=\"admin_list_04\" href=\"/admin/orderList\">주문 목록</a>                    \r\n");
      out.write("	                  </lI>                                                                                                \r\n");
      out.write("	              </ul>\r\n");
      out.write("                </div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"admin_content_wrap\">\r\n");
      out.write("    <div class=\"admin_content_subject\">\r\n");
      out.write("    	<span>상품 등록</span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"admin_content_main\">\r\n");
      out.write("    	<form action=\"/admin/goodsEnroll\" method=\"post\" id=\"enrollForm\">\r\n");
      out.write("    		<div class=\"form_section\">\r\n");
      out.write("    			<div class=\"form_section_title\">\r\n");
      out.write("    				<label>상품 이름</label>\r\n");
      out.write("    			</div>\r\n");
      out.write("    			<div class=\"form_section_content\">\r\n");
      out.write("    				<input name=\"vinName\">\r\n");
      out.write("    				<span class=\"ck_warn vinName_warn\">상품 이름을 입력해주세요.</span>\r\n");
      out.write("    			</div>\r\n");
      out.write("    		</div>             \r\n");
      out.write("    		<div class=\"form_section\">\r\n");
      out.write("    			<div class=\"form_section_title\">\r\n");
      out.write("    				<label>상품 카테고리</label>\r\n");
      out.write("    			</div>\r\n");
      out.write("    			<div class=\"form_section_content\">\r\n");
      out.write("    				<div class=\"cate_wrap\">\r\n");
      out.write("						<span>대분류</span>\r\n");
      out.write("						<select class=\"cate1\">\r\n");
      out.write("							<option selected value=\"none\">선택</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"cate_wrap\">\r\n");
      out.write("						<span>중분류</span>\r\n");
      out.write("						<select class=\"cate2\" name=\"cateCode\">\r\n");
      out.write("							<option selected value=\"none\">선택</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					<span class=\"ck_warn cateCode_warn\">카테고리를 선택해주세요.</span>\r\n");
      out.write("    			</div>\r\n");
      out.write("    		</div>          \r\n");
      out.write("    		<div class=\"form_section\">\r\n");
      out.write("    			<div class=\"form_section_title\">\r\n");
      out.write("    				<label>상품 가격</label>\r\n");
      out.write("    			</div>\r\n");
      out.write("    			<div class=\"form_section_content\">\r\n");
      out.write("    				<input name=\"vinPrice\" value=\"0\">\r\n");
      out.write("    				<span class=\"ck_warn vinPrice_warn\">상품 가격을 입력해주세요.</span>\r\n");
      out.write("    			</div>\r\n");
      out.write("    		</div>               \r\n");
      out.write("    		<div class=\"form_section\">\r\n");
      out.write("    			<div class=\"form_section_title\">\r\n");
      out.write("    				<label>상품 재고</label>\r\n");
      out.write("    			</div>\r\n");
      out.write("    			<div class=\"form_section_content\">\r\n");
      out.write("    				<input name=\"vinStock\" value=\"0\">\r\n");
      out.write("    				<span class=\"ck_warn vinStock_warn\">상품 재고를 입력해주세요.</span>\r\n");
      out.write("    			</div>\r\n");
      out.write("    		</div>          \r\n");
      out.write("    		<div class=\"form_section\">\r\n");
      out.write("    			<div class=\"form_section_title\">\r\n");
      out.write("    				<label>상품 할인율</label>\r\n");
      out.write("    			</div>\r\n");
      out.write("    			<div class=\"form_section_content\">\r\n");
      out.write("    				<input id=\"discount_interface\" maxlength=\"2\" value=\"0\">\r\n");
      out.write("					<input name=\"vinDiscount\" type=\"hidden\" value=\"0\">\r\n");
      out.write("					<span class=\"step_val\">할인된 가격 : <span class=\"span_discount\"></span></span>\r\n");
      out.write("    				<span class=\"ck_warn vinDiscount_warn\">1~99 숫자를 입력해주세요.</span>\r\n");
      out.write("    			</div>\r\n");
      out.write("    		</div>          		\r\n");
      out.write("    		<div class=\"form_section\">\r\n");
      out.write("    			<div class=\"form_section_title\">\r\n");
      out.write("    				<label>상품 소개</label>\r\n");
      out.write("    			</div>\r\n");
      out.write("    			<div class=\"form_section_content\">\r\n");
      out.write("    				<textarea name=\"vinInfo\" id=\"vinInfo_textarea\"></textarea>\r\n");
      out.write("    				<span class=\"ck_warn vinInfo_warn\">상품 소개를 입력해주세요.</span>\r\n");
      out.write("    			</div>\r\n");
      out.write("    		</div>\r\n");
      out.write("    		<div class=\"form_section\">\r\n");
      out.write("    			<div class=\"form_section_title\">\r\n");
      out.write("    				<label>상품 이미지</label>\r\n");
      out.write("    			</div>\r\n");
      out.write("    			<div class=\"form_section_content\">\r\n");
      out.write("    				<input type=\"file\" id =\"fileItem\" name='uploadFile' style=\"height: 30px;\">\r\n");
      out.write("    				<div id=\"uploadResult\">\r\n");
      out.write("    				\r\n");
      out.write("    				</div>\r\n");
      out.write("    			</div>\r\n");
      out.write("    		</div>\r\n");
      out.write("   		</form>\r\n");
      out.write("		<div class=\"btn_section\">\r\n");
      out.write("			<button id=\"cancelBtn\" class=\"btn\">취 소</button>\r\n");
      out.write(" 			<button id=\"enrollBtn\" class=\"btn enroll_btn\">등 록</button>\r\n");
      out.write(" 		</div> \r\n");
      out.write("    </div>  \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <div class=\"clearfix\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("		\r\n");
      out.write("		<!-- Footer 영역 -->\r\n");
      out.write("		<div class=\"footer_nav\">\r\n");
      out.write("			<div class=\"footer_nav_container\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>\r\n");
      out.write("						<a href=\"/shopinfo/aboutus\">ABOUT US</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<span class=\"line\">|</span>\r\n");
      out.write("					<li>\r\n");
      out.write("						<a href=\"/shopinfo/agreement\">AGREEMENT</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<span class=\"line\">|</span>\r\n");
      out.write("					<li>\r\n");
      out.write("						<a href=\"/shopinfo/policy\">PRIVACY POLICY</a>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div> <!-- class=\"footer_nav\" -->\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"footer\">\r\n");
      out.write("			<div class=\"footer_container\">\r\n");
      out.write("				<div class=\"footer_customer\">\r\n");
      out.write("					CUSTOMER CENTER\r\n");
      out.write("					<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<strong>010-1234-1234</strong>\r\n");
      out.write("					<br>\r\n");
      out.write("					MON-FRI 10:00~17:30		LUNCH 12:00~13:00\r\n");
      out.write("					<br>\r\n");
      out.write("					SAT / SUN / HOLIDAY CLOSE\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"footer_bank\">\r\n");
      out.write("					BANK INFO\r\n");
      out.write("					<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					신한 : 110-123-456789\r\n");
      out.write("					<br>\r\n");
      out.write("					농협 : 312-1234-1234-12\r\n");
      out.write("					<br>\r\n");
      out.write("					<strong>예금주 : 박은채</strong>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"footer_addr\">\r\n");
      out.write("					RETURN & EXCHANGE\r\n");
      out.write("					<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					서울특별시 강남구 압구정로 5-25\r\n");
      out.write("					<br>\r\n");
      out.write("					CJ대한통운(1588-1255)\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div> <!-- class=\"footer\" -->		\r\n");
      out.write("		<div class=\"footer_bottom\">\r\n");
      out.write("			<div class=\"footer_copy\">\r\n");
      out.write("				COMPANY : VINSHOP / OWNER : 박은채 / ADDRESS : 06000 서울특별시 강남구 압구정로 5-25\r\n");
      out.write("				<br>\r\n");
      out.write("				CALL : 010-1234-1234 / E-MAIL : pec6049@naver.com / BUSINESS LICENSE : 123-45-67890 / MALL ORDER LICENSE : 제2021-서울특별시-0000\r\n");
      out.write("				<br>\r\n");
      out.write("				COPYRIGHT © VINSHOP ALL RIGHTS RESERVED.\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"clearfix\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>	<!-- class=\"wrap\" -->\r\n");
      out.write("</div>	<!-- class=\"wrapper\" -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("	let enrollForm = $(\"#enrollForm\")\r\n");
      out.write("	\r\n");
      out.write("	/* 취소 버튼 */\r\n");
      out.write("	$(\"#cancelBtn\").click(function(){\r\n");
      out.write("		\r\n");
      out.write("		location.href=\"/admin/goodsManage\"\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	/* 상품 등록 버튼 */\r\n");
      out.write("	$(\"#enrollBtn\").on(\"click\",function(e){\r\n");
      out.write("		\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		\r\n");
      out.write("		/* 체크 변수 */\r\n");
      out.write("		let vinNameCk = false;\r\n");
      out.write("		let cateCodeCk = false;\r\n");
      out.write("		let priceCk = false;\r\n");
      out.write("		let stockCk = false;\r\n");
      out.write("		let discountCk = false;\r\n");
      out.write("		let infoCk = false;\r\n");
      out.write("		\r\n");
      out.write("		/* 체크 대상 변수 */\r\n");
      out.write("		let vinName = $(\"input[name='vinName']\").val();\r\n");
      out.write("		let cateCode = $(\"select[name='cateCode']\").val();\r\n");
      out.write("		let vinPrice = $(\"input[name='vinPrice']\").val();\r\n");
      out.write("		let vinStock = $(\"input[name='vinStock']\").val();\r\n");
      out.write("		let vinDiscount = $(\"#discount_interface\").val();	//사용자가 입력하는 <input>태그를 가리킴\r\n");
      out.write("		let vinInfo = $(\".bit p\").html();\r\n");
      out.write("	\r\n");
      out.write("		/* 공란 체크 */\r\n");
      out.write("		if(vinName){\r\n");
      out.write("			$(\".vinName_warn\").css('display','none');\r\n");
      out.write("			vinNameCk = true;\r\n");
      out.write("		} else {\r\n");
      out.write("			$(\".vinName_warn\").css('display','block');\r\n");
      out.write("			vinNameCk = false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(cateCode != 'none'){\r\n");
      out.write("			$(\".cateCode_warn\").css('display','none');\r\n");
      out.write("			cateCodeCk = true;\r\n");
      out.write("		} else {\r\n");
      out.write("			$(\".cateCode_warn\").css('display','block');\r\n");
      out.write("			cateCodeCk = false;\r\n");
      out.write("		}	\r\n");
      out.write("	\r\n");
      out.write("		if(vinPrice != 0){\r\n");
      out.write("			$(\".vinPrice_warn\").css('display','none');\r\n");
      out.write("			priceCk = true;\r\n");
      out.write("		} else {\r\n");
      out.write("			$(\".vinPrice_warn\").css('display','block');\r\n");
      out.write("			priceCk = false;\r\n");
      out.write("		}	\r\n");
      out.write("		\r\n");
      out.write("		if(vinStock != 0){\r\n");
      out.write("			$(\".vinStock_warn\").css('display','none');\r\n");
      out.write("			stockCk = true;\r\n");
      out.write("		} else {\r\n");
      out.write("			$(\".vinStock_warn\").css('display','block');\r\n");
      out.write("			stockCk = false;\r\n");
      out.write("		}		\r\n");
      out.write("	\r\n");
      out.write("		if(!isNaN(vinDiscount)){	//입력값이 문자인지 숫자인지 판단\r\n");
      out.write("			$(\".vinDiscount_warn\").css('display','none');\r\n");
      out.write("			discountCk = true;\r\n");
      out.write("		} else {\r\n");
      out.write("			$(\".vinDiscount_warn\").css('display','block');\r\n");
      out.write("			discountCk = false;\r\n");
      out.write("		}	\r\n");
      out.write("	\r\n");
      out.write("		if(vinInfo != '<br data-cke-filler=\"true\">'){\r\n");
      out.write("			$(\".vinInfo_warn\").css('display','none');\r\n");
      out.write("			infoCk = true;\r\n");
      out.write("		} else {\r\n");
      out.write("			$(\".vinInfo_warn\").css('display','block');\r\n");
      out.write("			infoCk = false;\r\n");
      out.write("		}	\r\n");
      out.write("	\r\n");
      out.write("		if(vinNameCk && cateCodeCk && priceCk && stockCk && discountCk && infoCk){\r\n");
      out.write("			//alert('통과');\r\n");
      out.write("			enrollForm.submit();\r\n");
      out.write("		} else {\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	/* 위지윅 적용 */\r\n");
      out.write("	/* 상품 소개 */\r\n");
      out.write("	ClassicEditor\r\n");
      out.write("		.create(document.querySelector('#vinInfo_textarea'))\r\n");
      out.write("		.catch(error=>{\r\n");
      out.write("			console.error(error);\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	/* 카테고리 */\r\n");
      out.write("	let cateList = JSON.parse('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cateList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("	\r\n");
      out.write("	let cate1Array = new Array();\r\n");
      out.write("	let cate2Array = new Array();\r\n");
      out.write("	let cate1Obj = new Object();\r\n");
      out.write("	let cate2Obj = new Object();\r\n");
      out.write("	\r\n");
      out.write("	let cateSelect1 = $(\".cate1\");		\r\n");
      out.write("	let cateSelect2 = $(\".cate2\");\r\n");
      out.write("	\r\n");
      out.write("	/* 카테고리 배열 초기화 메서드 */\r\n");
      out.write("	function makeCateArray(obj,array,cateList, tier){\r\n");
      out.write("		for(let i = 0; i < cateList.length; i++){\r\n");
      out.write("			if(cateList[i].tier === tier){\r\n");
      out.write("				obj = new Object();\r\n");
      out.write("				\r\n");
      out.write("				obj.cateName = cateList[i].cateName;\r\n");
      out.write("				obj.cateCode = cateList[i].cateCode;\r\n");
      out.write("				obj.cateParent = cateList[i].cateParent;\r\n");
      out.write("				\r\n");
      out.write("				array.push(obj);				\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 배열 초기화 */\r\n");
      out.write("	makeCateArray(cate1Obj,cate1Array,cateList,1);\r\n");
      out.write("	makeCateArray(cate2Obj,cate2Array,cateList,2);\r\n");
      out.write("	\r\n");
      out.write("	/* 대분류 <option> 태그 */\r\n");
      out.write("	for(let i = 0; i < cate1Array.length; i++){\r\n");
      out.write("		cateSelect1.append(\"<option value='\"+cate1Array[i].cateCode+\"'>\" + cate1Array[i].cateName + \"</option>\");\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 중분류 <option> 태그 */\r\n");
      out.write("	$(cateSelect1).on(\"change\",function(){\r\n");
      out.write("		\r\n");
      out.write("		let selectVal1 = $(this).find(\"option:selected\").val();	\r\n");
      out.write("		\r\n");
      out.write("		cateSelect2.children().remove();\r\n");
      out.write("		\r\n");
      out.write("		cateSelect2.append(\"<option value='none'>선택</option>\")\r\n");
      out.write("		\r\n");
      out.write("		for(let i = 0; i < cate2Array.length; i++){\r\n");
      out.write("			if(selectVal1 === cate2Array[i].cateParent){\r\n");
      out.write("				cateSelect2.append(\"<option value='\"+cate2Array[i].cateCode+\"'>\" + cate2Array[i].cateName + \"</option>\");	\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	/* 할인율 Input 설정 */\r\n");
      out.write("	$(\"#discount_interface\").on(\"propertychange change keyup paste input\", function(){\r\n");
      out.write("			\r\n");
      out.write("		let userInput = $(\"#discount_interface\");\r\n");
      out.write("		let discountInput = $(\"input[name='vinDiscount']\");\r\n");
      out.write("			\r\n");
      out.write("		let discountRate = userInput.val();					// 사용자가 입력할 할인값\r\n");
      out.write("		let sendDiscountRate = discountRate / 100;			// 서버에 전송할 할인값\r\n");
      out.write("		let goodsPrice = $(\"input[name='vinPrice']\").val();			// 원가\r\n");
      out.write("		let discountPrice = goodsPrice * (1 - sendDiscountRate);		// 할인가격\r\n");
      out.write("		\r\n");
      out.write("		if(!isNaN(discountRate)){\r\n");
      out.write("			$(\".span_discount\").html(discountPrice);	\r\n");
      out.write("			discountInput.val(sendDiscountRate);\r\n");
      out.write("		}	\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	/* 바로 상품가격을 수정해도 할인된 가격 출력 */\r\n");
      out.write("	$(\"input[name='vinPrice']\").on(\"change\", function(){\r\n");
      out.write("		\r\n");
      out.write("		let userInput = $(\"#discount_interface\");\r\n");
      out.write("		let discountInput = $(\"input[name='vinDiscount']\");\r\n");
      out.write("		\r\n");
      out.write("		let discountRate = userInput.val();					// 사용자가 입력한 할인값\r\n");
      out.write("		let sendDiscountRate = discountRate / 100;			// 서버에 전송할 할인값\r\n");
      out.write("		let goodsPrice = $(\"input[name='vinPrice']\").val();			// 원가\r\n");
      out.write("		let discountPrice = goodsPrice * (1 - sendDiscountRate);		// 할인가격\r\n");
      out.write("		\r\n");
      out.write("		if(!isNaN(discountRate)){\r\n");
      out.write("			$(\".span_discount\").html(discountPrice);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	/* 이미지 업로드 */\r\n");
      out.write("	$(\"input[type='file']\").on(\"change\", function(e){\r\n");
      out.write("		\r\n");
      out.write("		/* 이미지 존재시 삭제 */\r\n");
      out.write("		if($(\".imgDeleteBtn\").length > 0){\r\n");
      out.write("			deleteFile();\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		let formData = new FormData();\r\n");
      out.write("		let fileInput = $('input[name=\"uploadFile\"]');\r\n");
      out.write("		let fileList = fileInput[0].files;\r\n");
      out.write("		let fileObj = fileList[0];\r\n");
      out.write("		\r\n");
      out.write("		if(!fileCheck(fileObj.name, fileObj.size)) {\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		formData.append(\"uploadFile\", fileObj);\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: '/admin/uploadAjaxAction',\r\n");
      out.write("			processData: false,\r\n");
      out.write("			contentType: false,\r\n");
      out.write("			data: formData,\r\n");
      out.write("			type: 'POST',\r\n");
      out.write("			dataType: 'json',\r\n");
      out.write("			success : function(result) {\r\n");
      out.write("				console.log(result);\r\n");
      out.write("				showUploadImage(result);\r\n");
      out.write("			},\r\n");
      out.write("			error : function(result) {\r\n");
      out.write("				alert(\"이미지 파일이 아닙니다.\");\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	/* var, method related with attachFile */\r\n");
      out.write("	let regex = new RegExp(\"(.*?)\\.(jpg|png)$\");	//jpg 또는 png파일만 가능\r\n");
      out.write("	let maxSize = 1048576; //1MB\r\n");
      out.write("	\r\n");
      out.write("	function fileCheck(fileName, fileSize) {\r\n");
      out.write("		if(fileSize >= maxSize) {\r\n");
      out.write("			alert(\"파일 사이즈 초과\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if(!regex.test(fileName)) {\r\n");
      out.write("			alert(\"해당 종류의 파일은 업로드 할 수 없습니다.\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 이미지 출력 */\r\n");
      out.write("	function showUploadImage(uploadResultArr){\r\n");
      out.write("		/* 전달받은 데이터 검증 */\r\n");
      out.write("		if(!uploadResultArr || uploadResultArr.length == 0) {\r\n");
      out.write("			return\r\n");
      out.write("		}\r\n");
      out.write("		let uploadResult = $(\"#uploadResult\");\r\n");
      out.write("		let obj = uploadResultArr[0];\r\n");
      out.write("		let str = \"\";\r\n");
      out.write("		let fileCallPath = encodeURIComponent(obj.uploadPath.replace(/\\\\/g, '/') + \"/s_\" + obj.uuid + \"_\" + obj.fileName);\r\n");
      out.write("		\r\n");
      out.write("		str += \"<div id = 'result_card'>\";\r\n");
      out.write("		str += \"<img src='/display?fileName=\" + fileCallPath + \"'>\";\r\n");
      out.write("		str += \"<div class='imgDeleteBtn' data-file='\" + fileCallPath + \"'>x</div>\";\r\n");
      out.write("		str += \"<input type='hidden' name='imageList[0].fileName' value='\"+ obj.fileName +\"'>\";\r\n");
      out.write("		str += \"<input type='hidden' name='imageList[0].uuid' value='\"+ obj.uuid +\"'>\";\r\n");
      out.write("		str += \"<input type='hidden' name='imageList[0].uploadPath' value='\"+ obj.uploadPath +\"'>\";\r\n");
      out.write("		str += \"</div>\";	\r\n");
      out.write("		\r\n");
      out.write("   		uploadResult.append(str);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 이미지 삭제 버튼 동작 */\r\n");
      out.write("	$(\"#uploadResult\").on(\"click\", \".imgDeleteBtn\", function(e) {\r\n");
      out.write("		\r\n");
      out.write("		deleteFile();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	/* 파일 삭제 메서드 */\r\n");
      out.write("	function deleteFile() {\r\n");
      out.write("		let targetFile = $(\".imgDeleteBtn\").data(\"file\");\r\n");
      out.write("		let targetDiv = $(\"#result_card\");\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : '/admin/deleteFile',\r\n");
      out.write("			data : {fileName : targetFile},\r\n");
      out.write("			dataType : 'text',\r\n");
      out.write("			type : 'POST',\r\n");
      out.write("			success : function(result) {\r\n");
      out.write("				console.log(result);\r\n");
      out.write("				\r\n");
      out.write("				targetDiv.remove();\r\n");
      out.write("				$(\"input[type='file']\").val(\"\");\r\n");
      out.write("			},\r\n");
      out.write("			error : function(result) {\r\n");
      out.write("				console.log(result);\r\n");
      out.write("				\r\n");
      out.write("				alert(\"파일을 삭제하지 못하였습니다.\")\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("</script>  \r\n");
      out.write("\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
